1. 데이터 구성 및 기본 정보 확인
- daegu_service_pcell_time csv를 활용
- 컬럼명, 상위 5개, 하위 5개, info 정보를 확인

In [15]:
import os
import pandas as pd
from IPython.display import display

DATA_DIR = "."
files = ["daegu_service_pcell_time_pop_202510.csv"]

for f in files:
    path = os.path.join(DATA_DIR, f)
    print(f, "=>", "Ok" if os.path.exists(path) else "Not FOUND")

def inspect_csv(path, nrows_preview=2000):
    print("\n"+"="*90)
    print(f"[FILE] {os.path.basename(path)}")

    encodings_to_try = [None, "utf-8", "cp949"]
    df_preview = None
    used_encoding = None
    last_err = None

    for enc in encodings_to_try:
        try:
            df_preview = pd.read_csv(path, nrows=nrows_preview, encoding=enc)
            used_encoding = enc
            break
        except UnicodeDecodeError as e:
            raise last_err
    
    if df_preview.shape[1] == 1 and "|" in str(df_preview.columns[0]):
        df_preview = pd.read_csv(path, nrows=nrows_preview, encoding=None if used_encoding=="default" else used_encoding, sep = "|")
        print("Detected '|' delimeter -> reloaded with sep'|'")

    enc_label = "default" if used_encoding is None else used_encoding

    print(f"Encoding used: {used_encoding}")
    print(f"Preview shape: {df_preview.shape}")

    print("\n[Columns]")
    print(list(df_preview.columns))

    print("\n[Head_5]")
    display(df_preview.head(5))

    print("\n[Tail_5]")
    display(df_preview.tail(5))

    print("\n[Info]")
    df_preview.info()

    return df_preview

preview_dfs = {}
for f in files:
    path = os.path.join(DATA_DIR, f)
    if os.path.exists(path):
        preview_dfs[f] = inspect_csv(path)

daegu_service_pcell_time_pop_202510.csv => Ok

==========================================================================================
[FILE] daegu_service_pcell_time_pop_202510.csv
Detected '|' delimeter -> reloaded with sep'|'
Encoding used: None
Preview shape: (2000, 77)

[Columns]
['STD_YMD', 'HCODE', 'X_COORD', 'Y_COORD', 'H_T_00', 'H_T_01', 'H_T_02', 'H_T_03', 'H_T_04', 'H_T_05', 'H_T_06', 'H_T_07', 'H_T_08', 'H_T_09', 'H_T_10', 'H_T_11', 'H_T_12', 'H_T_13', 'H_T_14', 'H_T_15', 'H_T_16', 'H_T_17', 'H_T_18', 'H_T_19', 'H_T_20', 'H_T_21', 'H_T_22', 'H_T_23', 'W_T_00', 'W_T_01', 'W_T_02', 'W_T_03', 'W_T_04', 'W_T_05', 'W_T_06', 'W_T_07', 'W_T_08', 'W_T_09', 'W_T_10', 'W_T_11', 'W_T_12', 'W_T_13', 'W_T_14', 'W_T_15', 'W_T_16', 'W_T_17', 'W_T_18', 'W_T_19', 'W_T_20', 'W_T_21', 'W_T_22', 'W_T_23', 'V_T_00', 'V_T_01', 'V_T_02', 'V_T_03', 'V_T_04', 'V_T_05', 'V_T_06', 'V_T_07', 'V_T_08', 'V_T_09', 'V_T_10', 'V_T_11', 'V_T_12', 'V_T_13', 'V_T_14', 'V_T_15', 'V_T_16', 'V_T_17', 'V_T_18', 'V_T_19', 'V_T_20', 'V_T_21', 'V_T_22', 'V_T_23', 'BLOCK_CD']

[Head_5]

,STD_YMD,HCODE,X_COORD,Y_COORD,H_T_00,H_T_01,H_T_02,H_T_03,H_T_04,H_T_05,...,V_T_15,V_T_16,V_T_17,V_T_18,V_T_19,V_T_20,V_T_21,V_T_22,V_T_23,BLOCK_CD
0,20251001,2711051700,1.099384e+06,1.764529e+06,15.88,16.37,16.73,16.90,16.93,16.68,...,11.65,11.61,9.89,9.33,9.12,7.85,6.50,5.64,4.33,22010560100020000020
1,20251001,2711051700,1.099434e+06,1.764629e+06,9.32,9.60,9.82,9.91,9.93,9.79,...,6.84,6.81,5.80,5.47,5.35,4.60,3.81,3.31,2.54,22010700100010000001
2,20251001,2711051700,1.099434e+06,1.764679e+06,5.06,5.22,5.33,5.38,5.39,5.31,...,3.71,3.70,3.15,2.97,2.91,2.50,2.07,1.80,1.38,22010700100010000001
3,20251001,2711051700,1.099484e+06,1.764629e+06,13.73,14.16,14.47,14.61,14.64,14.42,...,10.08,10.04,8.55,8.07,7.88,6.78,5.62,4.87,3.74,22010700100010000001
4,20251001,2711051700,1.099534e+06,1.764629e+06,33.11,34.13,34.88,35.22,35.28,34.77,...,24.29,24.20,20.62,19.45,19.01,16.36,13.54,11.75,9.02,22010700100010000001

[Tail_5]

,STD_YMD,HCODE,X_COORD,Y_COORD,H_T_00,H_T_01,H_T_02,H_T_03,H_T_04,H_T_05,...,V_T_15,V_T_16,V_T_17,V_T_18,V_T_19,V_T_20,V_T_21,V_T_22,V_T_23,BLOCK_CD
1995,20251006,2711051700,1.099484e+06,1.764029e+06,28.79,29.61,30.36,30.66,30.75,30.50,...,22.08,21.85,22.59,22.88,23.29,22.45,21.28,18.66,17.20,22010700100030000001
1996,20251006,2711051700,1.099484e+06,1.764079e+06,15.56,16.00,16.40,16.56,16.62,16.48,...,11.93,11.80,12.20,12.36,12.59,12.13,11.50,10.08,9.29,22010700100030000001
1997,20251006,2711051700,1.099484e+06,1.764129e+06,17.16,17.64,18.09,18.27,18.32,18.18,...,13.16,13.02,13.46,13.63,13.88,13.37,12.68,11.12,10.25,22010700100030000001
1998,20251006,2711051700,1.099484e+06,1.764179e+06,26.15,26.90,27.57,27.85,27.93,27.70,...,20.05,19.84,20.51,20.78,21.16,20.39,19.32,16.95,15.62,22010700100030000001
1999,20251006,2711051700,1.099484e+06,1.764229e+06,73.35,75.44,77.34,78.11,78.35,77.72,...,56.25,55.67,57.54,58.28,59.35,57.18,54.21,47.54,43.81,22010700100030000001

[Info]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 77 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   STD_YMD   2000 non-null   int64
 1   HCODE     2000 non-null   int64
 2   X_COORD   2000 non-null   float64
 3   Y_COORD   2000 non-null   float64
 4   H_T_00    2000 non-null   float64
 5   H_T_01    2000 non-null   float64
 6   H_T_02    2000 non-null   float64
 7   H_T_03    2000 non-null   float64
 8   H_T_04    2000 non-null   float64
 9   H_T_05    2000 non-null   float64
 10  H_T_06    2000 non-null   float64
 11  H_T_07    2000 non-null   float64
 12  H_T_08    2000 non-null   float64
 13  H_T_09    2000 non-null   float64
 14  H_T_10    2000 non-null   float64
 15  H_T_11    2000 non-null   float64
 16  H_T_12    2000 non-null   float64
 17  H_T_13    2000 non-null   float64
 18  H_T_14    2000 non-null   float64
 19  H_T_15    2000 non-null   float64
 20  H_T_16    2000 non-null   float64
 21  H_T_17    2000 non-null   float64
 22  H_T_18    2000 non-null   float64
 23  H_T_19    2000 non-null   float64
 24  H_T_20    2000 non-null   float64
 25  H_T_21    2000 non-null   float64
 26  H_T_22    2000 non-null   float64
 27  H_T_23    2000 non-null   float64
 28  W_T_00    2000 non-null   float64
 29  W_T_01    2000 non-null   float64
 30  W_T_02    2000 non-null   float64
 31  W_T_03    2000 non-null   float64
 32  W_T_04    2000 non-null   float64
 33  W_T_05    2000 non-null   float64
 34  W_T_06    2000 non-null   float64
 35  W_T_07    2000 non-null   float64
 36  W_T_08    2000 non-null   float64
 37  W_T_09    2000 non-null   float64
 38  W_T_10    2000 non-null   float64
 39  W_T_11    2000 non-null   float64
 40  W_T_12    2000 non-null   float64
 41  W_T_13    2000 non-null   float64
 42  W_T_14    2000 non-null   float64
 43  W_T_15    2000 non-null   float64
 44  W_T_16    2000 non-null   float64
 45  W_T_17    2000 non-null   float64
 46  W_T_18    2000 non-null   float64
 47  W_T_19    2000 non-null   float64
 48  W_T_20    2000 non-null   float64
 49  W_T_21    2000 non-null   float64
 50  W_T_22    2000 non-null   float64
 51  W_T_23    2000 non-null   float64
 52  V_T_00    2000 non-null   float64
 53  V_T_01    2000 non-null   float64
 54  V_T_02    2000 non-null   float64
 55  V_T_03    2000 non-null   float64
 56  V_T_04    2000 non-null   float64
 57  V_T_05    2000 non-null   float64
 58  V_T_06    2000 non-null   float64
 59  V_T_07    2000 non-null   float64
 60  V_T_08    2000 non-null   float64
 61  V_T_09    2000 non-null   float64
 62  V_T_10    2000 non-null   float64
 63  V_T_11    2000 non-null   float64
 64  V_T_12    2000 non-null   float64
 65  V_T_13    2000 non-null   float64
 66  V_T_14    2000 non-null   float64
 67  V_T_15    2000 non-null   float64
 68  V_T_16    2000 non-null   float64
 69  V_T_17    2000 non-null   float64
 70  V_T_18    2000 non-null   float64
 71  V_T_19    2000 non-null   float64
 72  V_T_20    2000 non-null   float64
 73  V_T_21    2000 non-null   float64
 74  V_T_22    2000 non-null   float64
 75  V_T_23    2000 non-null   float64
 76  BLOCK_CD  2000 non-null   object
dtypes: float64(74), int64(2), object(1)
memory usage: 1.2+ MB

2. 시간대별 평균 컬럼 생성
- 대구 전체에 대한 통계
- 07-11 / 12-18 / 19-22 / 23-06 시간대별 통계 산출

In [9]:
import pandas as pd
import numpy as np

FILE = "daegu_service_pcell_time_pop_202510.csv"

TIME_BANDS = {
    "07_11" : list(range(7,12)),
    "12_18" : list(range(12,19)),
    "19_22" : list(range(19,23)),
    "23_06" : [23, 0, 1, 2, 3, 4, 5, 6],
}
bands = list(TIME_BANDS.keys())

base_cols = ["STD_YMD", "HCODE", "X_COORD", "Y_COORD"]
H_cols = [f"H_T_{h:02d}" for h in range(24)]
W_cols = [f"W_T_{h:02d}" for h in range(24)]
V_cols = [f"V_T_{h:02d}" for h in range(24)]
usecols = base_cols + H_cols + W_cols + V_cols

dtypes = {
    "STD_YMD" : "int64",
    "HCODE" : "int64",
    "X_COORD" : "float64",
    "Y_COORD" : "float64",
}
for c in H_cols + W_cols + V_cols:
    dtypes[c] = "float32"

df = pd.read_csv(FILE, sep="|", usecols=usecols, dtype=dtypes)
print(df.shape)

def add_band_means(df: pd.DataFrame, prefix: str):
    for band, hours in TIME_BANDS.items():
        cols = [f"{prefix}_T_{h:02d}" for h in hours]
        cols = [c for c in cols if c in df.columns]
        df[f"{prefix}_B_{band}"] = df[cols].mean(axis=1)
    return df

df = add_band_means(df, "H") #거주인구
df = add_band_means(df, "W") #직장인구
df = add_band_means(df, "V") #방문인구

for b in bands:
    df[f"ALL_B_{b}"] = df[f"H_B_{b}"] +df[f"W_B_{b}"] +df[f"V_B_{b}"]

ordered = []
for b in bands:
    ordered += [f"H_B_{b}", f"W_B_{b}", f"V_B_{b}", f"ALL_B_{b}"]

daegu_overall_mean = df[ordered].mean().to_frame("DAEGU_OVERALL_MEAN")
display(daegu_overall_mean.round(3))

(6450046, 76)

             DAEGU_OVERALL_MEAN
H_B_07_11                 8.207
W_B_07_11                 1.702
V_B_07_11                 2.289
ALL_B_07_11              12.198
H_B_12_18                 6.529
W_B_12_18                 2.198
V_B_12_18                 3.409
ALL_B_12_18              12.135
H_B_19_22                 8.959
W_B_19_22                 0.631
V_B_19_22                 2.922
ALL_B_19_22              12.512
H_B_23_06                10.898
W_B_23_06                 0.197
V_B_23_06                 1.396
ALL_B_23_06              12.491

- geopandas 설치 시도 -> 폐쇄망이라 설치 불가
- QGIS 를 통해 도면 생성하고 python에서는 통계 csv 생성 단계까지만 진행

In [21]:
import sys
!{sys.executable} -m pip install -U pip

Requirement already satisfied: pip in c:\programdata\anaconda3\envs\python3.10\lib\site-packages (24.2)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002045DE73EE0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002045DEA4250>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002045DEA4400>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002045DEA45B0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002045DEA4760>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

In [22]:
!conda --version

conda 24.5.0

In [23]:
!conda install -c conda-forge geopandas -y #폐쇄망이라 설치가 안됨

Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... failed

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD949F1A0>: Failed to resolve 'conda.anaconda.org' ([Errno 11002] getaddrinfo failed)")': /conda-forge/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CC200>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CCB00>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/notices.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CCDD0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/notices.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CCE90>: Failed to resolve 'conda.anaconda.org' ([Errno 11002] getaddrinfo failed)")': /conda-forge/notices.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD070>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/notices.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD250>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/notices.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD130>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/notices.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD3D0>: Failed to resolve 'conda.anaconda.org' ([Errno 11002] getaddrinfo failed)")': /conda-forge/notices.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD580>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/notices.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD7C0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/notices.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CD8E0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/notices.json

ERROR conda.notices.fetch:get_channel_notice_response(73): Request error <HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/notices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CDB50>: Failed to resolve 'conda.anaconda.org' ([Errno 11002] getaddrinfo failed)"))> for channel: conda-forge url: https://conda.anaconda.org/conda-forge/notices.json
ERROR conda.notices.fetch:get_channel_notice_response(73): Request error <HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/r/notices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CDD00>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)"))> for channel: defaults url: https://repo.anaconda.com/pkgs/r/notices.json
ERROR conda.notices.fetch:get_channel_notice_response(73): Request error <HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/msys2/notices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CDE80>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)"))> for channel: defaults url: https://repo.anaconda.com/pkgs/msys2/notices.json
ERROR conda.notices.fetch:get_channel_notice_response(73): Request error <HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/notices.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCD94CE000>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)"))> for channel: defaults url: https://repo.anaconda.com/pkgs/main/notices.json
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFC650>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFCCE0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFD0A0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFD400>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFD9D0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFD670>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE0C0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFDF70>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFDE50>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE4B0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE360>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE240>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE780>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFED20>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/main/win-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFEB40>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFE8A0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFEFC0>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CCDABFEE40>: Failed to resolve 'repo.anaconda.com' ([Errno 11002] getaddrinfo failed)")': /pkgs/msys2/win-64/repodata.json.zst


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\cli\main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\notices\core.py", line 127, in wrapper
        return_value = func(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\cli\main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\cli\install.py", line 377, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\core\solve.py", line 153, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\core\solve.py", line 222, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda_libmamba_solver\solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda_libmamba_solver\index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda_libmamba_solver\index.py", line 332, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
        raise self._exception
      File "C:\ProgramData\anaconda3\Lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda_libmamba_solver\index.py", line 254, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\gateways\repodata\__init__.py", line 749, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\gateways\repodata\__init__.py", line 789, in fetch_latest
        cache.load_state()
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\gateways\repodata\__init__.py", line 585, in load_state
        self.load(state_only=True)
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\gateways\repodata\__init__.py", line 532, in load
        with self.lock("r+") as state_file:
      File "C:\ProgramData\anaconda3\Lib\contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\conda\gateways\repodata\__init__.py", line 651, in lock
        with self.cache_path_state.open(mode) as state_file, lock(state_file):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\pathlib.py", line 1013, in open
        return io.open(self, mode, buffering, encoding, errors, newline)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\anaconda3\\pkgs\\cache\\5afe41e9.info.json'

`$ C:\ProgramData\anaconda3\Scripts\conda-script.py install -c conda-forge geopandas -y`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=python3.10
                CONDA_EXE=C:\ProgramData\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\anaconda3\envs\python3.10
    CONDA_PROMPT_MODIFIER=(python3.10)
         CONDA_PYTHON_EXE=C:\ProgramData\anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\빅데이터활용센터
               LD_PRELOAD=<not set>
                     PATH=c:\ProgramData\anaconda3\envs\python3.10;C:\ProgramData\anaconda3\envs
                          \python3.10;C:\ProgramData\anaconda3\envs\python3.10\Library\mingw-
                          w64\bin;C:\ProgramData\anaconda3\envs\python3.10\Library\usr\bin;C:\Pr
                          ogramData\anaconda3\envs\python3.10\Library\bin;C:\ProgramData\anacond
                          a3\envs\python3.10\Scripts;C:\ProgramData\anaconda3\envs\python3.10\bi
                          n;C:\ProgramData\anaconda3\condabin;C:\Program Files\Common Files\Orac
                          le\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wb
                          em;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\Open
                          SSH;C:\Program Files\Java\jdk-23\bin\server\bin;C:\Program
                          Files\PuTTY;C:\Program Files\Bandizip;C:\ProgramData\anaconda3;C:\Prog
                          ramData\anaconda3\Library;C:\ProgramData\anaconda3\Library\bin;C:\Prog
                          ramData\anaconda3\Scripts;C:\Users\빅데이터활용센터\AppData\Local\Programs\Pyt
                          hon\Python312\Scripts;C:\Users\빅데이터활용센터\AppData\Local\Programs\Python\
                          Python312;C:\Users\빅데이터활용센터\AppData\Local\Microsoft\WindowsApps;.;C:\U
                          sers\빅데이터활용센터\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program
                          Files\JetBrains\PyCharm Community Edition 2024.1.4\bin;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=utf-8
         PYTHONUNBUFFERED=1
               PYTHONUTF8=1
    PYTHON_FROZEN_MODULES=on
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\ProgramData\anaconda3\envs\python3.10\Library\ssl\cacert.pem
   VSCODE_CODE_CACHE_PATH=C:\Users\빅데이터활용센터\AppData\Roaming\Code\CachedData\38c31bc77e0dd6ae88a4
                          e9cc93428cc27a56ba40

     active environment : python3.10
    active env location : C:\ProgramData\anaconda3\envs\python3.10
            shell level : 1
       user config file : C:\Users\빅데이터활용센터\.condarc
 populated config files : C:\Users\빅데이터활용센터\.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.5.0=0
                          __win=0=0
       base environment : C:\ProgramData\anaconda3  (writable)
      conda av data dir : C:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\anaconda3\pkgs
                          C:\Users\빅데이터활용센터\.conda\pkgs
                          C:\Users\빅데이~1\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\anaconda3\envs

3. 지역별 통계 컬럼 생성
- 원본 csv와의 HCODE 매핑을 통해 구/군 매칭
- 오류 확인을 위한 결측 비율 확인

In [11]:
def map_sigungu_from_hcode(hcode):
    hcode = str(hcode)
    if hcode.startswith("27110"):
        return "중구"
    elif hcode.startswith("27140"):
        return "동구"
    elif hcode.startswith("27170"):
        return "서구"
    elif hcode.startswith("27200"):
        return "남구"
    elif hcode.startswith("27230"):
        return "북구"
    elif hcode.startswith("27260"):
        return "수성구"
    elif hcode.startswith("27290"):
        return "달서구"
    elif hcode.startswith("27710"):
        return "달성군"
    else:
        return None
    
df["SIGUNGU_NM"] = df["HCODE"].apply(map_sigungu_from_hcode)
df["SIGUNGU_NM"].value_counts()

bands = list(TIME_BANDS.keys())

ordered = []
for b in bands:
    ordered += [
        f"H_B_{b}",
        f"W_B_{b}",
        f"V_B_{b}",
        f"ALL_B_{b}"
    ]

gu_mean = (
    df.groupby("SIGUNGU_NM")[ordered]
    .mean()
    .round(3)
    .reset_index()
)

display(gu_mean)
print("gu_mean shape: ", gu_mean.shape)

print("결측비율확인:", df["SIGUNGU_NM"].isna().mean())
print(df["SIGUNGU_NM"].value_counts(dropna=False).head(20))

print(df["HCODE"].head(10).tolist())
print(df["HCODE"].dtype)

,SIGUNGU_NM,H_B_07_11,W_B_07_11,V_B_07_11,ALL_B_07_11,H_B_12_18,W_B_12_18,V_B_12_18,ALL_B_12_18,H_B_19_22,W_B_19_22,V_B_19_22,ALL_B_19_22,H_B_23_06,W_B_23_06,V_B_23_06,ALL_B_23_06
0,남구,17.452000,3.410,5.269,26.132000,13.626,4.468,7.063,25.158001,18.461000,1.261,5.876000,25.597000,22.905001,0.447,3.143,26.496000
1,달서구,19.850000,4.089,4.961,28.900000,15.713,5.162,7.015,27.889999,21.791000,1.539,6.617000,29.947001,26.674999,0.476,3.227,30.378000
2,달성군,3.097000,0.648,0.652,4.397000,2.630,0.781,0.907,4.318000,3.451000,0.193,0.625000,4.269000,3.939000,0.060,0.343,4.342000
3,동구,7.191000,1.236,2.063,10.490000,5.773,1.659,3.123,10.555000,7.954000,0.483,2.419000,10.857000,9.511000,0.152,1.178,10.841000
4,북구,12.823000,2.662,3.444,18.929001,10.221,3.325,4.939,18.486000,14.008000,0.973,4.325000,19.306000,17.049999,0.347,2.127,19.524000
5,서구,19.200001,4.252,5.525,28.976999,15.344,5.382,7.308,28.034000,21.492001,1.349,6.547000,29.386999,26.318001,0.478,3.472,30.268000
6,수성구,13.628000,2.386,3.494,19.507000,10.435,3.112,5.299,18.847000,14.499000,1.003,5.162000,20.664000,18.194000,0.280,2.272,20.746000
7,중구,20.216999,10.315,13.557,44.089001,15.036,15.469,28.545,59.049999,21.334000,4.218,22.381001,47.932999,27.368999,0.944,8.218,36.532001

gu_mean shape:  (8, 17)
결측비율확인: 0.18447031230474945
SIGUNGU_NM
달성군     1750291
None    1189842
동구      1026286
북구       730887
수성구      648892
달서구      627843
서구       203577
남구       184822
중구        87606
Name: count, dtype: int64
[2711051700, 2711051700, 2711051700, 2711051700, 2711051700, 2711051700, 2711051700, 2711051700, 2711051700, 2711051700]
int64

4. 통계 결과 저장

In [12]:
pcell_cols = [
    "X_COORD", "Y_COORD", "HCODE", "SIGUNGU_NM",
    "H_B_07_11", "H_B_12_18", "H_B_19_22", "H_B_23_06",
    "W_B_07_11", "W_B_12_18", "W_B_19_22", "W_B_23_06",
    "V_B_07_11", "V_B_12_18", "V_B_19_22", "V_B_23_06",
    "ALL_B_07_11", "ALL_B_12_18", "ALL_B_19_22", "ALL_B_23_06"
]

df_pcell = df[pcell_cols]

df_pcell.to_csv(
    "daegu_pcell_timeband_202510.csv",
    index=False,
    encoding="utf-8-sig"
)

5. 그리드 생성
- 좌표를 500m 단위 버킷팅
- 같은 격자에 속한 값 평균
- 결과 -> 격자 1칸 = 1행

In [13]:
GRID_SIZE = 500

df["GX"] = (df["X_COORD"] // GRID_SIZE) * GRID_SIZE
df["GY"] = (df["Y_COORD"] // GRID_SIZE) * GRID_SIZE

grid_mean = (
    df.groupby(["GX", "GY"])
    .agg({
        "ALL_B_07_11": "mean",
        "ALL_B_12_18": "mean",
        "ALL_B_19_22": "mean",
        "ALL_B_23_06": "mean",
    })
    .reset_index()
)

grid_mean.head()

          GX         GY  ALL_B_07_11  ALL_B_12_18  ALL_B_19_22  ALL_B_23_06
0  1076500.0  1745500.0     0.095239     0.093263     0.077274     0.076185
1  1077000.0  1743500.0     0.197903     0.193771     0.160565     0.158495
2  1077000.0  1744000.0     0.250428     0.245635     0.203589     0.201529
3  1077000.0  1744500.0     0.090895     0.089419     0.072688     0.071903
4  1077000.0  1745000.0     0.162548     0.159217     0.130718     0.128367

In [14]:
grid_mean.to_csv(
    "daegu_grid_500m_mean.csv",
    index = False,
    encoding = "utf-8"
)